name: simulasi_slot
description: Aplikasi Edukasi Bahaya Judi Online.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Core
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.1.6
  
  # UI & Animasi
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  flutter_animated_button: ^2.0.4
  infinite_carousel: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  
  # State Management
  provider: ^6.1.2
  intl: ^0.20.2


  

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/patterns/cherry_win_patterns.json
    - assets/patterns/lemon_win_patterns.json
    - assets/patterns/diamond_win_patterns.json
    - assets/patterns/money_win_patterns.json
    - assets/patterns/orange_win_patterns.json
    - assets/patterns/symbol_map.json
    - assets/patterns/lose_patterns.json

 